class TaskInterruptedException(Exception):
    """Исключение для прерывания задачи."""
    pass