class TaskInterruptedError(Exception):
    """An exception to interrupt the task."""
    pass
